services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        networks:
            - pizza 
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./src:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - /etc/letsencrypt:/etc/letsencrypt
          - ./nginx/logs:/var/log/nginx
        depends_on:
          - php

    php:
        build:
          context: .
          dockerfile: php-dockerfile
        user: "${USER_ID}:${GROUP_ID}"
        container_name: php
        volumes:
          - ./src:/var/www/html
        ports:
          - "9000:9000"
        networks:
          - pizza

    composer:
      image: composer:latest
      user: "${USER_ID}:${GROUP_ID}"
      container_name: composer
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      networks:
        - pizza 

    npm:
      image: node:latest
      user: "${USER_ID}:${GROUP_ID}"
      container_name: npm
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      entrypoint: ['npm']
      networks:
        - pizza 

networks:
    pizza:
        driver: bridge
